apiVersion: v1
kind: Pod
metadata:
  name: wasm-rust
spec:
  containers:
  - name: wasm-c
    image: ghcr.io/adawolfs/wasm-rust:latest
  nodeSelector:
    kubernetes.io/arch: wasm32-wasi
  tolerations:
  - effect: NoExecute
    key: kubernetes.io/arch
    operator: Equal
    value: wasm32-wasi   # or wasm32-wasmcloud according to module target arch
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: wasm32-wasi 